E_Commerce/Models/auction.cs
namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
 


    [Table("auction")]
    public partial class auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public auction()
        {
            bid = new HashSet<bid>();
            User = new HashSet<User>();
        }
        
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid id { get; set; }

        [StringLength(50)]
        public string title { get; set; }

        public byte[] picture { get; set; }

        public int? duration { get; set; }

        public double? startPrice { get; set; }

        public double? currentPrice { get; set; }

        public DateTime? createdAt { get; set; }

        public DateTime? openedAt { get; set; }

        public DateTime? closedAt { get; set; }

        [StringLength(10)]
        public string status { get; set; }

        public Guid bidId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bid> bid { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}

E_Commerce/Controllers/AuctionController.cs
using E_Commerce.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.IO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.SignalR;
using E_Commerce.Hubs;
using System.Data;

namespace E_Commerce.Controllers
{
    public class AuctionController : Controller
    {
        // GET: Auction
        private AuctionsHub auctionsHub = new AuctionsHub();
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        public ActionResult Home(MessageInfo? message)
        {
            log.Info("Auction/Home has been fired.");
            //page with search and add button
            ViewBag.StatusMessage =
               message == MessageInfo.ChangeSuccess ? "Successfully opened a auction."
               : message == MessageInfo.ChangeUnsuccess ? "Error, something went wrong."
               : message == MessageInfo.AuctionFinished ? "Error, the auction is not in the READY state."
               : message == MessageInfo.AuctionClosed ? "Auction has been successfully closed."
                : message == MessageInfo.AuctionOver ? "The auction has finished."
                 : message == MessageInfo.BidSuccess ? "Your bid has been successfully placed."
                 : message == MessageInfo.NoTokens ? "Not enough tokens."
                 : message == MessageInfo.RequiredFields ? "All fields are required."
                 : message == MessageInfo.SuccessCreation ? "Auction successfully created."
               : "";
            return View();
        }

        //open an auction that has been created
        /*
         * I show the list of all auctions that can be opened
         * II btn that changes the state of the auction--->javascript
         * */
        [System.Web.Mvc.Authorize(Roles = "admin")]
        public ActionResult OpenAdmin(int? page)
        {
            log.Info("Auction/OpenAdmin has been fired.");
            using (var context = new E_Commerce.Models.AuctionsDB())
            {
                IEnumerable<E_Commerce.Models.auction> auctions = from auc in context.auction
                                                                  where auc.status == "READY"
                                                                  select auc;
                int pageSize = AdminParams.N;
                int pageNum = 1;
                if (page != null)
                {
                    pageNum = (int)page;
                }

                auctions = auctions.OrderBy(s => s.createdAt);
                return View(auctions.ToPagedList(pageNum, pageSize));
            }
        }
        //TODO
        [System.Web.Mvc.Authorize(Roles ="admin")]
        public ActionResult OpenConfirm(Guid idAukcije)
        {
            log.Info("Auction/OpenConfirm has been fired.");
            if (idAukcije == null)
            {
                log.Error("Auction/Home idAuction is null.");
                return RedirectToAction("Home", new { Message = MessageInfo.ChangeUnsuccess });
            }
            using(var context=new AuctionsDB())
            {
                using(var trans = context.Database.BeginTransaction(IsolationLevel.Serializable))
                {
                    try
                    {

                        auction auction = context.auction.Find(idAukcije);
                        if (auction == null)
                        {
                            throw new Exception();
                        }
                        if (!auction.status.Contains("READY"))
                        {
                            log.Error("Auction/Home auction is not ready.");
                            throw new Exception();
                        }

                        //otvaranje
                        auction.status = "OPENED";
                        auction.openedAt = DateTime.Now;
                        auction.closedAt = DateTime.Now.AddSeconds((double)auction.duration);
                        context.Entry(auction).State = System.Data.Entity.EntityState.Modified;
                        context.SaveChanges();
                        trans.Commit();
                        var myHub = GlobalHost.ConnectionManager.GetHubContext<AuctionsHub>();
                        myHub.Clients.All.updateStatus(idAukcije);
                        return RedirectToAction("Home", new { Message = MessageInfo.ChangeSuccess });
                    }
                    catch(Exception ex)
                    {
                        log.Error("Error with opening auction");
                        trans.Rollback();
                    }
                }
                
            }
            return RedirectToAction("Home", new { Message = MessageInfo.ChangeUnsuccess });
            
        }
       public void CheckFinish()
        {
            var myHub = GlobalHost.ConnectionManager.GetHubContext<AuctionsHub>();
            //provera da li su zatvorene neke od otvorenih aukcija
            using (var context=new AuctionsDB())
            {
                using(var trans = context.Database.BeginTransaction(IsolationLevel.Serializable))
                {
                    try
                    {
                        IEnumerable<auction> auctions = (from a in context.auction
                                                         where a.status == "OPENED"
                                                         select a).ToList();
                        foreach (var auction in auctions)
                        {
                            DateTime now = DateTime.Now;
                            DateTime closing = (DateTime)auction.closedAt;
                            if (now > closing)
                            {
                                auction.status = "COMPLETED";
                                context.Entry(auction).State = System.Data.Entity.EntityState.Modified;
                                context.SaveChanges();
                                myHub.Clients.All.closeAuction(auction.id);
                            }
                        }
                        trans.Commit();
                    }
                    catch(Exception e)
                    {
                        log.Error("Error with finnishing auction.");
                        trans.Rollback();
                    }
                }
                
            }
            
        }
        //TODO
        [System.Web.Mvc.Authorize]
        [HttpPost]
        public ActionResult Bid(Guid idAukcije, string sTitle, string sPriceLow, string sPriceHigh, string sStatus, int sPage)
        {
            CheckFinish();
            log.Info("Auction/Bid has been fired.");
            
            int result=auctionsHub.SendBid(idAukcije,User.Identity.GetUserId());

            if (result==1)
            {
                return RedirectToAction("Index", new {
                    title = sTitle,
                    priceLow = sPriceLow,
                    priceHigh = sPriceHigh,
                    status = sStatus,
                    page=sPage,
                    Message = MessageInfo.AuctionOver
                });
            }
            else if (result == 2)
            {
                return RedirectToAction("Index", new
                {
                    title = sTitle,
                    priceLow = sPriceLow,
                    priceHigh = sPriceHigh,
                    status = sStatus,
                    page = sPage,
                    Message = MessageInfo.NoTokens
                });
            }
            else if (result == 3)
            {
                return RedirectToAction("Index", new
                {
                    title = sTitle,
                    priceLow = sPriceLow,
                    priceHigh = sPriceHigh,
                    status = sStatus,
                    page = sPage,
                    Message = MessageInfo.ChangeUnsuccess
                });
            }
            else
            {
                return RedirectToAction("Index", new
                {
                    title = sTitle,
                    priceLow = sPriceLow,
                    priceHigh = sPriceHigh,
                    status = sStatus,
                    page = sPage,
                    Message = MessageInfo.BidSuccess
                });
            }

        }

        [System.Web.Mvc.Authorize]
        [HttpPost]
        public void FinishAuction(Guid id)
        {
            //da li mora actionresult da vrati----check
            log.Info("Auction/FinishAuction has been fired.");
            if (id == null)
            {
                return ;
            }
            using (var context = new AuctionsDB())
            {
                using(var trans = context.Database.BeginTransaction(IsolationLevel.Serializable))
                {
                    try
                    {
                        auction auction = context.auction.Find(id);
                        if (auction == null)
                        {
                            return;
                        }
                        if (!auction.status.Contains("OPENED"))
                        {
                            return;
                        }

                        //otvaranje
                        auction.status = "COMPLETED";
                        context.Entry(auction).State = System.Data.Entity.EntityState.Modified;
                        context.SaveChanges();
                        trans.Commit();
                        var myHub = GlobalHost.ConnectionManager.GetHubContext<AuctionsHub>();
                        myHub.Clients.All.closeAuction(id);
                    }
                    catch(Exception e)
                    {
                        log.Error("Error with finnishing auction(called)");

E_Commerce/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Commerce.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

E_Commerce/Views/Auction/Create.cshtml
@model E_Commerce.Models.auctionNEW
@{ 
    ViewBag.Title = "New Auction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Cart view section -->
<section id="aa-myaccount">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-myaccount-area">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="aa-myaccount-register">
                                <h4>Add new auctionu</h4>
                                @using (Html.BeginForm("ConfirmCreate", "Auction", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal aa-login-form" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.title, "Title of auction: ", new { @class = "col-md-2 control-label" })
                                        <div class="col-md-8">
                                            @Html.TextBoxFor(m => m.title, new { @class = "form-control" })
                                        </div>
                                        <div class="col-md-2">
                                            @Html.ValidationMessageFor(m => m.title)
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.duration, "Duration in seconds: ", new { @class = "col-md-2 control-label" })
                                        <div class="col-md-8">
                                            @Html.TextBoxFor(m => m.duration, new { @class = "form-control" })
                                        </div>
                                        <div class="col-md-2">
                                            @Html.ValidationMessageFor(m => m.duration)
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.startPrice, "Starting price: ", new { @class = "col-md-2 control-label" })
                                        <div class="col-md-8">
                                            @Html.TextBoxFor(m => m.startPrice, new { @class = "form-control" })
                                        </div>
                                        <div class="col-md-2">
                                            @Html.ValidationMessageFor(m => m.startPrice)
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.picture, "Picture of product: ", new { @class = "col-md-2 control-label" })
                                        <div class="col-md-8">
                                            @Html.TextBoxFor(model => model.picture, new { type = "file" })
                                        </div>
                                        <div class="col-md-2">
                                            @Html.ValidationMessageFor(m => m.picture)
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" class="btn btn-default" value="Create new auction" />
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / Cart view section -->

E_Commerce/Views/Auction/Home.cshtml
@{
    ViewBag.Title = "Auctions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!---->
<h6>@ViewBag.StatusMessage</h6>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="aa-myaccount-area">
                <div class="row">
                    <h2>Search auctions</h2>
                    <div class="col-md-12">
                        <div class="aa-myaccount-register">
                            @using (Html.BeginForm("Index", "Auction", FormMethod.Get, new { enctype = "multipart/form-data", @class = "form-horizontal aa-login-form" }))
                            {
                            <p>
                                Title of the auctions: <br />
                                <input type="text" name="title" />
                                <br />Lowest price: <br />
                                <input type="text" name="priceLow" />
                                <br />Highest price: <br />
                                <input type="text" name="priceHigh" />
                                <br />Status of the auctions: <br />
                                <!--<input type="text" name="status" />-->
                                <select class="form-control" id="status" name="status">
                                    <option value="N">Select status</option>
                                    <option value="R">READY</option>
                                    <option value="O">OPENED</option>
                                    <option value="C">COMPLETED</option>
                                </select>

                            </p>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" class="btn btn-default" value="Search" />
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
                @if (Request.IsAuthenticated)
                {
                    <div class="row">
                        <h2>Create new auction</h2>
                        <button type="button" class="btn btn-default">@Html.ActionLink("Create new auction", "Create", "Auction")</button>
                    </div>
                }

                <!--mozda izbaciti i dodati kod search-a-->
                @if (Request.IsAuthenticated && User.IsInRole("admin"))
                {
                    <div class="row">
                        <h2>Open auction that is pending</h2>
                        <button type="button" class="btn btn-default">@Html.ActionLink("Open auction", "OpenAdmin", "Auction")</button>
                    </div>
                }

                @if (Request.IsAuthenticated)
                {
                    <div class="row">
                        <h2>Auctions I have won</h2>
                        <button type="button" class="btn btn-default">@Html.ActionLink("Show", "Won", "Auction")</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


<!--End of search section-->
<!--Button add new auction-->

E_Commerce/Views/Auction/OpenAdmin.cshtml
@model PagedList.IPagedList<E_Commerce.Models.auction>
@using PagedList.Mvc;
@using E_Commerce.Helper
@{
    ViewBag.Title = "OpenAdmin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of auctions that are ready</h2>
<!-- Products section -->
<section id="aa-product">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="aa-product-area">
                        <div class="aa-product-inner">
                            <!-- start page numbering -->
                            <div class="page-numbering">
                                @Html.PagedListPager(Model, page => Url.Action("OpenAdmin", new { page}))
                            </div>
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <!-- Start all products -->
                                <div class="tab-pane fade in active" id="men">
                                    <ul class="aa-product-catg">
                                        @foreach (var item in Model)
                                        {


                                            <!-- start single product item -->
                                            <li class="col-md-4 col-xs-12" style="border:10px">
                                                <figure>
                                                    @{
                                                        var baseIm = Convert.ToBase64String(item.picture);
                                                        var imageSrc = String.Format("data:image/jpg;base64,{0}", baseIm);
                                                    }
                                                    <img src="@imageSrc" style="width:200px; height:120px" alt="slika_proizvoda" class="product-image" />

                                                </figure>
                                                <figcaption>
                                                    <h4 class="aa-product-title">@Html.DisplayFor(modelItem => item.title)</h4>
                                                    <span>@Html.DisplayFor(modelItem => item.createdAt)</span><br />
                                                    <span>@Html.DisplayFor(modelItem => item.status)</span>

                                                    @using (Html.BeginForm("OpenConfirm", "Auction", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal aa-login-form" }))
                                                    {
                                                        <input type="hidden" name="idAukcije" value="@item.id" />

                                                        <input type="submit" class="btn btn-success" value="Open" />
                                                    }
                                                </figcaption>
                                            </li>
                                        }
                                    </ul>
                                </div>
                                <!-- / all products -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / Products section -->

E_Commerce/Views/Auction/Won.cshtml
@model PagedList.IPagedList<E_Commerce.Models.auction>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Won";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Won auctions</h2>

<!-- Products section -->
<section id="aa-product">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="aa-product-area">
                        <div class="aa-product-inner">
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div class="page-numbering">
                                    @Html.PagedListPager(Model, page => Url.Action("Won",
                                                    new { page }))
                                </div>
                                <!-- Start all products -->
                                <div class="tab-pane fade in active" id="men">
                                    <ul class="aa-product-catg">
                                        @foreach (var item in Model)
                                        {
                                            <!-- start single product item -->
                                            <li class="col-md-4 col-xs-12" style="border:10px">
                                                <figure>
                                                    <a class="aa-product-img" href="@Url.Action("Show", "Auction", new { id = item.id })">
                                                        @{
                                                            var baseIm = Convert.ToBase64String(item.picture);
                                                            var imageSrc = String.Format("data:image/jpg;base64,{0}", baseIm);
                                                        }
                                                        <img src="@imageSrc" style="width:200px; height:120px" alt="slika_proizvoda" class="product-image" />
                                                    </a>

                                                </figure>
                                                <figcaption>
                                                    <h4 class="aa-product-title">@Html.DisplayFor(modelItem => item.title)</h4>
                                                    <span class="aa-product-price">@Html.DisplayFor(modelItem => item.currentPrice)</span><br />
                                                    <span> @Html.DisplayFor(modelItem => item.status)</span>

                                                </figcaption>

                                                <!-- product badge -->
                                            </li>
                                        }
                                    </ul>
                                </div>
                                <!-- / all products -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>